#!/bin/sh

find output -type f -delete
cd output/

../tomcat < ../input/Input.dat  
../PrepPlot < ./Input_PrepPlotCD_self_generated.dat

cd ..
#rm Input_PrepPlotCD_self_generated.dat  
#rm CurrentsFile CurrentDrive_Main_Output.dat CurrentDrive_Output4Ernesto.dat 
#rm temporarynames temporarynames2
