#!/bin/bash


cd output
mkdir -p 1para_scan
rm -rf 1para_scan/*

Z=1  #Hydrogen
Z=2  #Helium
####-----
b_start=10
b_end=60
b_step=1
####-----
b_values=$(awk "BEGIN {for(i=$b_start;i<=$b_end;i+=$b_step) print i}")

pairs=()

for b in $b_values; do
    pairs+=("$b,")
    
####Con_scan####
    #a=$(echo "scale=4; 1 - $Z * $b" | bc)
    #pairs+=("0$a, $b,")
####Con_scan####3IONS
    #a=$(echo "scale=4; (1 - $Z * $b)/2" | bc)
    #pairs+=("0$a, 0$a, $b,")
done


for idx in "${!pairs[@]}"; do
#####change input file####
    pair="${pairs[$idx]}"   
    #sed -i "s|frek=.*|frek=${pair}|" ../input/Input.dat
    sed -i "s|ntor=.*|ntor=${pair}|" ../input/Input.dat
    #sed -i "s|concentr=.*|concentr=${pair}|" ../input/Input.dat

#####Run TOMCAT####
    ../tomcat < ../input/Input.dat  
    ../PrepPlot < ./Input_PrepPlotCD_self_generated.dat
     
#####save results#### 
    target_folder="1para_scan/$((idx+1))"
    mkdir -p "$target_folder"
    find . -maxdepth 1 -type f -not -name ".*" -not -name "*.sh" -exec mv {} "$target_folder/" \;
    
    echo "Results save to $target_folder"
    sleep 1.5
done

echo "Simulations finished"
cd ..


