#!/bin/bash


cd output
mkdir -p 1para_scan

pairs=("0.90, 0.10," "0.80, 0.12," "0.70, 0.20,") 

for idx in "${!pairs[@]}"; do
    #change input file
    pair="${pairs[$idx]}"   
    sed -i "s/concentr=[0-9]\+\.[0-9]\+, [0-9]\+\.[0-9]\+,/concentr=${pair}/" ../input/Input.dat

    #Run TOMCAT
    ../TOMCAT.out < ../input/Input.dat  
    ../PrepPlot.out < ./Input_PrepPlotCD_self_generated.dat
     
    #save results 
    target_folder="1para_scan/$((idx+1))"
    mkdir -p "$target_folder"
    find . -maxdepth 1 -type f -exec mv {} "$target_folder" \;
    
    sleep 2
    echo "concentr=${pair} Run TOMCAT，Results move to $target_folder"
    sleep 1
done

cd ..



