#!/bin/bash

cd output 

mkdir -p 2para_scan
rm -rf 2para_scan/*

# parameter setup
Zb=1  # Hydrogen
Zc=2  #Helium
Zc=3  #Lithium

b_start=0.20
b_end=0.50
b_step=0.01
c_start=0.01
c_end=0.10
c_step=0.01


b_values=$(awk "BEGIN {for(i=$b_start;i<=$b_end;i+=$b_step) print i}")
c_values=$(awk "BEGIN {for(i=$c_start;i<=$c_end;i+=$c_step) print i}")

countb=1

for b in $b_values; do
    #sed -i "s|ntor=.*|ntor=${b},|" ../input/Input.dat 
    countc=1 
    for c in $c_values; do

####Con_scan####
        #a=$(echo "scale=4; 1 - $Zc * $c" | bc) 
	a=$(echo "scale=4; 1 - $Zb * $b - $Zc * $c" | bc)      
        if [[ $a == .* ]]; then
            a="0$a"
        fi      
        sed -i "s|concentr=.*|concentr=${a}, ${b}, ${c},|" ../input/Input.dat
####---------------###########      

#####Run T
OMCAT####
        ../tomcat < ../input/Input.dat    
        ../PrepPlot < ./Input_PrepPlotCD_self_generated.dat

#####save results####  
        # creater the folder
        target_folder="2para_scan/$countb/$countc"
        mkdir -p "$target_folder"
       
        find . -maxdepth 1 -type f -not -name ".*" -not -name "*.sh" -exec mv {} "$target_folder/" \;
        
        echo "Results save to $target_folder"
	((countc++))
        sleep 1.5
    done
    ((countb++))
done

echo "Simulations finished"
cd ..
